# IMPORT NUMPY

In [116]:
import numpy as np

# BASIC ARRAY CREATION

In [117]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

# BASIC LIST CREATION

In [118]:
l = [1,2,3,4]
l

[1, 2, 3, 4]

# ARRAY CONTAIN ONLY ONE TYPE OF DATA

In [119]:
a = [1,2,3.5,"Hello"]
a

[1, 2, 3.5, 'Hello']

# IF DATA IS STRING SO ALL DATA CONVERT INTO STRING 
IF ONLY ONE DATA OR ITEM IS IN STRING SO ALL ARRAY CONVERT INTO STRING

In [120]:
b = np.array([1,2,3.4,"Hello"])
b

array(['1', '2', '3.4', 'Hello'], dtype='<U32')

# IF DATA IS FLOAT SO ALL DATA CONVERT INTO FLOAT
- IF ONLY ONE DATA OR ITEM IS IN FLOAT SO ALL ARRAY CONVERT INTO FLOAT
- `ARRAY CONTAIN ONLY ONE TYPE OF DATA/ITEM`

In [121]:
b = np.array([1,2,3.4])
b

array([1. , 2. , 3.4])

# COMMAON LIST

In [122]:
c = [[1,2,3],[4,5,6],[7,8,9]]
print(c)
type(c)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

# CONVERT LIST INTO ARRAY

In [123]:
np.array(c)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array genration function

In [124]:
d = np.arange(1,11)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- `ZEROS ARRAY GENRATION`

In [125]:
d = np.zeros((4,8))
d

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

- `ONE'S ARRAY GENRATIONM`

In [126]:
d = np.ones((8,8))
d

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

## Breakdown of the function(LINESPACE).
- **0:** The starting point of the sequence.
- **10:** The stopping point of the sequence.
- **20:** The total number of elements to generate.

In [127]:
d = np.linspace(0,10,20)
d

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# RANDOM GENRATION FUNCTION

# NumPy Random Generation Cheat Sheet

### 1. `np.random.rand(10)` ➡️ The "Percentage" Machine
* **What it does:** Generates **10 decimals** between **0 and 1** (e.g., `0.15`, `0.84`, `0.02`).
* **The Rule:** Every decimal between 0 and 1 has an **equal chance** of being picked. It will never be negative and never reaches exactly 1.
* **Analogy:** Pulling 10 random percentages out of a hat (0% to 99.9%).

### 2. `np.random.randn(10)` ➡️ The "Bell Curve" Machine
* **What it does:** Generates **10 decimals** that can be positive or negative (e.g., `-1.2`, `0.5`, `-0.1`).
* **The Rule:** It centers around **0**. Numbers close to 0 are highly likely to be picked, while numbers far away (like `-3` or `+3`) are rare.
* **Analogy:** Throwing darts at a bullseye. Most hits crowd the center (`0`), with a few drifting left or right.

### 3. `np.random.randint(10, 20, 10)` ➡️ The "Whole Number" Machine
* **What it does:** Generates **10 whole numbers** (integers) from **10 up to 19**.
* **The Rule:** `randint(start, stop, count)`. It includes the start number but **excludes the stop number**.
* **Analogy:** Rolling a 10-sided die labeled `10` through `19`, exactly 10 times.

---

### Quick Comparison
* **`rand`**: Only **positive** decimals (0 to 1). Flat distribution.
* **`randn`**: **Positive & negative** decimals. Bell curve distribution around 0.
* **`randint`**: Only **whole numbers** in your custom range. Flat distribution.


In [128]:
np.random.rand(10)

array([0.47433613, 0.91521044, 0.94250795, 0.30491995, 0.06958605,
       0.07637707, 0.89506505, 0.13116748, 0.57592207, 0.54754861])

In [129]:
np.random.randn(10)

array([ 0.35085995, -1.39426138,  0.26730624,  1.64761928, -1.89815596,
       -0.31848513,  0.04016352, -1.83382095,  0.04860729,  0.29916441])

In [130]:
np.random.randint(10,20,10)

array([15, 17, 11, 17, 15, 11, 16, 16, 18, 17], dtype=int32)

# ARRAY ATTRIBUTES

# NumPy Array Attributes Cheat Sheet

Array attributes are **built-in properties** of a NumPy array that tell you about its shape, size, memory, and data type. You do **not** use parentheses `()` at the end of these (use `arr.shape`, not `arr.shape()`).

---

### 1. `arr.ndim` ➡️ The "Dimensions" Counter
* **What it tells you:** The number of axes (dimensions) the array has.
* **Easy Guide:** 
  * `1` = A flat line of numbers (Vector)
  * `2` = A grid with rows and columns (Matrix)
  * `3` = A cube/stack of grids (3D Tensor)

### 2. `arr.shape` ➡️ The "Grid Sizes" Tuple
* **What it tells you:** A tuple of integers showing the size of the array along each dimension.
* **Easy Guide:** For a 2D grid, it returns `(rows, columns)`. If it returns `(3, 5)`, it means your grid has 3 rows and 5 columns.

### 3. `arr.size` ➡️ The "Total Elements" Counter
* **What it tells you:** The total number of items inside the entire array.
* **Easy Guide:** It multiplies all the numbers in `arr.shape` together. For a `(3, 5)` shape array, the size is exactly `15`.

### 4. `arr.dtype` ➡️ The "Data Type" Checker
* **What it tells you:** The exact kind of data stored in the array (e.g., `int64`, `float64`, `bool`).
* **Easy Guide:** NumPy arrays can only hold **one type of data at a time**. This attribute tells you if your array is full of whole numbers, decimals, or text.

### 5. `arr.itemsize` & `arr.nbytes` ➡️ The "Memory" Trackers
* **`arr.itemsize`:** The memory size (in bytes) of **one single element** in the array. (An `int64` element takes up 8 bytes).
* **`arr.nbytes`:** The **total memory size** (in bytes) used by the entire array. 
* **Easy Formula:** `nbytes` = `size` × `itemsize`

---

### Quick Visual Reference

| Attribute | What it answers | Example Output |
| :--- | :--- | :--- |
| **`.ndim`** | How many dimensions? | `2` |
| **`.shape`** | What are the dimensions? | `(3, 4)` |
| **`.size`** | How many total items? | `12` |
| **`.dtype`** | What kind of data is inside? | `int32` |
| **`.itemsize`**| How many bytes per item? | `4` |
| **`.nbytes`** | Total bytes used in RAM? | `48` |


In [131]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [132]:
arr.ndim

2

In [133]:
arr.shape

(3, 3)

In [134]:
arr.size

9

In [135]:
arr.dtype

dtype('int64')

In [136]:
arr.itemsize

8

In [137]:
arr.nbytes

72

# ARRAY METHODS

# NumPy Array Methods Cheat Sheet

Array methods are **actions** you perform on an array to change its layout, find statistics, or modify its values. They always end with parentheses `()`.

---

### 1. Layout & Shape Changers
* **`arr.reshape(rows, cols)`** ➡️ Changes the grid layout without changing the data. For example, turning a flat line of 12 numbers into a `(3, 4)` grid.
* **`arr.flatten()`** ➡️ Collapses any multi-dimensional grid back down into a single, flat 1D line of numbers.
* **`arr.transpose()`** (or **`arr.T`**) ➡️ Flips the array. It turns all rows into columns and all columns into rows.

### 2. Math & Statistics (The Aggregators)
* **`arr.min()` / `arr.max()`** ➡️ Finds the lowest or highest value in the entire array.
* **`arr.sum()`** ➡️ Adds all the numbers in the array together to give you one grand total.
* **`arr.mean()`** ➡️ Calculates the average value of all numbers in the array.
* **`arr.std()`** ➡️ Calculates the Standard Deviation (how spread out the numbers are from the average).

### 3. Finding Locations
* **`arr.argmin()`** ➡️ Tells you the **index position** (location) of the minimum value, instead of the value itself.
* **`arr.argmax()`** ➡️ Tells you the **index position** (location) of the maximum value. Excellent for finding "where" the peak is.

---

### Pro-Tip: The `axis` Parameter
For statistical methods (`sum`, `max`, `mean`, etc.), you can calculate by row or column instead of the whole grid:
* **`axis=0`** ➡️ Computes the operation down each **column** (collapses rows).
* **`axis=1`** ➡️ Computes the operation across each **row** (collapses columns).

| Method | What it does | Example (on 2D array) |
| :--- | :--- | :--- |
| **`arr.reshape(2, 3)`** | Changes grid shape | Transforms a 6-element array into 2 rows, 3 cols |
| **`arr.max(axis=0)`** | Maximums | Finds the highest number in *each column* |
| **`arr.argmax()`** | Index of max | Returns `4` (meaning the max item is at index 4) |
| **`arr.flatten()`** | Flattens grid | Turns any matrix into a simple 1D list |


In [138]:
arr.min()

np.int64(1)

In [139]:
arr.max()

np.int64(9)

In [140]:
arr.sum()

np.int64(45)

In [141]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [142]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [143]:
arr.mean()

np.float64(5.0)

In [144]:
arr.std()

np.float64(2.581988897471611)

In [145]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
arr.argmax()

np.int64(8)

In [147]:
arr.argmin()

np.int64(0)

In [148]:
arr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# RESHAPING AND RESIZING

# NumPy Reshaping vs. Resizing Cheat Sheet

Both operations change the layout (dimensions) of an array, but they handle memory and the underlying data very differently.

---

### 1. `arr.reshape(rows, cols)` ➡️ The "Rearranger"
* **What it does:** Changes the grid layout **without** changing or copying the data. It just gives you a new view of the same numbers.
* **The Golden Rule:** The total number of elements **must stay exactly the same**. You can reshape a flat line of 12 elements into a `(3, 4)` grid or a `(2, 6)` grid because 3 × 4 = 12 and 2 × 6 = 12.
* **The Magic `-1` Trick:** If you don't want to do the math for a dimension, put `-1`. NumPy will calculate it for you! 
  * *Example:* `arr.reshape(2, -1)` on 12 elements automatically becomes a `(2, 6)` grid.

### 2. `arr.resize(new_shape)` ➡️ The "Size Modifier"
* **What it does:** Directly modifies the **original array permanently**. It can make an array larger or smaller.
* **The Rules for Mismatched Sizes:**
  * If the new shape is **smaller** than the original, it chops off the extra numbers.
  * If the new shape is **larger** than the original, it expands the array and fills the new spaces with zeros `0`.
* **Important:** This operates in-place, meaning you just call `arr.resize(3, 4)` and it updates `arr` automatically (it returns `None`).

---

### Key Differences at a Glance

| Feature | `arr.reshape()` | `arr.resize()` |
| :--- | :--- | :--- |
| **Modifies Original?** | ❌ No (Returns a new view) |  Yes (Changes it in-place) |
| **Element Count Rule**| ⚠️ Must match exactly | 🔄 Can be smaller or larger |
| **What if it's larger?**| ❌ Throws an error | 🆕 Fills new spots with `0` |
| **Syntax Style** | `new_arr = arr.reshape(3, 4)` | `arr.resize((3, 4))` *(Note the extra parenthetic tuple)* |

---

### Quick Code Reminders for Your Notebook
```python
# To flatten any matrix back to a 1D line:
arr.reshape(-1)

# To add a brand new empty dimension (e.g., converting 1D vector to 2D column matrix):
arr[:, np.newaxis]
```


In [149]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [150]:
arr.reshape(6,5) # ALWAYS CHECK PARAMETERS

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# NUMPY INDEXING AND SLICING OF VERTORS

# NumPy Vector Indexing & Slicing Cheat Sheet (1D Arrays)

Vectors are one-dimensional arrays (a single row/line of numbers). Indexing is how you grab **one specific item**, while slicing is how you cut out a **range of items**.

---

### 1. Vector Indexing ➡️ Grabbing One Element
Just like Python lists, NumPy arrays use **zero-based indexing** (counting starts at `0`).

* **`arr[0]`** ➡️ Grabs the **first** element.
* **`arr[3]`** ➡️ Grabs the **fourth** element.
* **`arr[-1]`** ➡️ Grabs the **last** element (negative indices count backward from the end).
* **`arr[-2]`** ➡️ Grabs the **second-to-last** element.

### 2. Vector Slicing ➡️ Cutting Out a Range
The formula for slicing is: **`arr[start : stop : step]`**
* ⚠️ **The Stop Rule:** The `start` index is included, but the `stop` index is **excluded** (up to, but not including).
* 🔄 **Blank Defaults:** If you leave `start` or `stop` blank, NumPy assumes you mean the very beginning or the very end.

**Common Slicing Recipes:**
* **`arr[2:5]`** ➡️ Elements from index 2 up to index 4 (stops before 5).
* **`arr[:3]`** ➡️ Grabs everything from the **beginning** up to index 2.
* **`arr[4:]`** ➡️ Grabs everything from index 4 all the way to the **end**.
* **`arr[:]`** ➡️ Grabs the **entire** array (creates a shallow copy/view).
* **`arr[::2]`** ➡️ Grabs every **second** element (steps by 2).
* **`arr[::-1]`** ➡️ Clever trick to **reverse** the entire vector.

---

### 🚨 Crucial NumPy Behavior: Slices are Views, Not Copies!
In normal Python lists, taking a slice creates a brand-new list. **In NumPy, a slice is just a "window" (view) into the original array.**

If you modify a slice, **you will permanently change the original array!**

```python
# To modify a slice safely without breaking the original data, use .copy():
sub_array = arr[2:6].copy()
```

---

### Quick Syntax Lookup Table
Assuming `arr = np.array([10, 20, 30, 40, 50, 60])`:

| Code | What it grabs | Result |
| :--- | :--- | :--- |
| `arr[1]` | Second element | `20` |
| `arr[-1]` | Last element | `60` |
| `arr[1:4]` | Indices 1, 2, 3 | `[20, 30, 40]` |
| `arr[::3]` | Start to end, step 3 | `[10, 40]` |


In [151]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [152]:
arr[6]     # [STAR : END: STEPS]

np.int64(17)

In [153]:
arr[1:5]

array([12, 13, 14, 15])

In [154]:
arr[:5]

array([11, 12, 13, 14, 15])

In [155]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [156]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

# NUMPY INDEXING AND SLICING OF MATRIXS

# NumPy Matrix Indexing & Slicing Cheat Sheet (2D Arrays)

Matrices have two dimensions: **Rows** (dimension 0) and **Columns** (dimension 1). 
Instead of using two sets of brackets like standard Python lists (`matrix[r][c]`), NumPy uses a single set of brackets with a comma separator: **`matrix[row, column]`**.

---

### 1. Matrix Indexing ➡️ Grabbing One Element or One Row
Think of it like coordinates on a map: `[row_index, column_index]`

* **`matrix[0, 0]`** ➡️ Grabs the single element at the very top-left corner (Row 0, Col 0).
* **`matrix[2, 3]`** ➡️ Grabs the element in the **3rd row, 4th column** (remember 0-based counting).
* **`matrix[1]`** (or `matrix[1, :]`) ➡️ Grabs the **entire second row** as a flat 1D vector.
* **`matrix[:, 2]`** ➡️ Grabs the **entire third column** as a vector. *(The `:` means "all rows")*

### 2. Matrix Slicing ➡️ Cutting Out Sub-Grids
To cut out a section of a matrix, apply the `[start:stop]` slicing logic to **both sides of the comma**:

\[\text{matrix}[\text{row\_start}:\text{row\_stop} \ , \ \text{col\_start}:\text{col\_stop}]\]

**Common Sub-Grid Recipes:**
* **`matrix[0:2, 0:3]`** ➡️ Grabs rows 0 and 1, and columns 0, 1, and 2. (A 2 × 3 sub-matrix).
* **`matrix[:2, 2:]`** ➡️ Grabs the top-right corner of the matrix (First 2 rows, and from column 2 to the end).
* **`matrix[1:, :2]`** ➡️ Grabs the bottom-left corner of the matrix.

---

### Visual Grid Cheat Sheet
Imagine a 3 × 3 matrix:
\[\begin{pmatrix} 10 & 11 & 12 \\ 20 & 21 & 22 \\ 30 & 31 & 32 \end{pmatrix}\]

| Syntax Example | What it targets visually | What it returns |
| :--- | :--- | :--- |
| `matrix[1, 2]` | Single item at row 1, col 2 | `22` |
| `matrix[2, :]` | The entire bottom row | `[30, 31, 32]` |
| `matrix[:, 0]` | The entire first column | `[10, 20, 30]` |
| `matrix[:2, 1:]` | Top-right 2 × 2 block | `[[11, 12], [21, 22]]` |

---

### 💡 Pro-Tip: Double Bracket vs. Comma
* `matrix[1][2]` ❌ **Slow / Legacy:** Python first pulls the whole row `1`, then extracts element `2` from it. 
* `matrix[1, 2]`  **Fast / Efficient:** NumPy directly checks the memory address of that exact element. Always use the comma syntax.


In [157]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [159]:
arr[0]

array([1, 2, 3, 4, 5])

In [160]:
arr [5]

array([26, 27, 28, 29, 30])

In [161]:
arr[0,0]

np.int64(1)

In [162]:
arr[4,3]

np.int64(24)

In [163]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [164]:
arr[2:3]

array([[11, 12, 13, 14, 15]])

In [165]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [166]:
arr[:,0:1]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21],
       [26]])

# BOOLEAN INDEXING

# NumPy Boolean Indexing 

Boolean indexing allows you to search through an array and **filter out only the numbers that meet a specific condition** (e.g., "give me all numbers greater than 50"). 

---

### 1. How It Works (The 2-Step Process)
NumPy handles filtering behind the scenes in two quick steps:

1. **The Mask:** When you apply a condition to an array (like `arr > 5`), NumPy tests every single element and returns a grid of **True / False** values. This is called a **Boolean Mask**.
2. **The Filter:** When you pass that mask back into the array brackets `arr[mask]`, NumPy keeps the elements where it sees `True` and throws away the `False` ones.

```python
arr = np.array([10, 20, 30, 40])

# Step 1: Create the Mask
mask = arr > 25       # Returns: array([False, False,  True,  True])

# Step 2: Filter the Array
result = arr[mask]    # Returns: array([30, 40])

# Shortcuts: You usually do this in one single clean line!
result = arr[arr > 25]
```

### 2. Combining Multiple Conditions
To combine conditions, you **cannot** use Python's standard `and` / `or` words. You must use **bitwise operators** and wrap each individual condition in **parentheses `()`**.

* **`&` (And)** ➡️ Both conditions must be True.
  * `arr[(arr > 10) & (arr < 30)]`
* **`|` (Or)** ➡️ At least one condition must be True.
  * `arr[(arr == 10) | (arr == 40)]`
* **`~` (Not)** ➡️ Inverts the condition (turns True to False and vice versa).
  * `arr[~(arr > 20)]` (Grabs numbers 20 or less)

### 3. Modifying Values Using Conditions
Boolean indexing is incredibly powerful because you can use it to **instantly overwrite** specific numbers in your array.

```python
# Replace all negative numbers in an array with zero:
arr[arr < 0] = 0

# Cap all high numbers at a maximum value of 100:
arr[arr > 100] = 100
```

---

### Quick Syntax Reference Table

| Syntax Example | What it reads as | Result Type |
| :--- | :--- | :--- |
| `arr > 5` | "Is the element greater than 5?" | A **True/False mask** matching original shape |
| `arr[arr > 5]` | "Extract elements greater than 5" | A **1D array** containing only matching numbers |
| `arr[arr % 2 == 0]`| "Extract all even numbers" | A **1D array** of even numbers |

*💡 **Note:** Even if you perform boolean indexing on a 2D matrix, filtering out numbers will always collapse the output into a flat **1D array**, because rows and columns break when individual elements are removed!*


In [167]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [168]:
bool_index = arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [169]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# ARRAY OPERATIONS

# NumPy Array Operations & Broadcasting

NumPy performs math operations instantly across entire arrays without using slow Python `for` loops. This blindingly fast execution is powered by **vectorization** and **broadcasting**.

---

### 1. Element-by-Element Arithmetic
When you perform operations on two arrays of the **exact same shape**, NumPy automatically pairs up the elements at the corresponding index positions and performs the math.

```python
a = np.array([10, 20, 30])
b = np.array([1,  2,  3])

a + b  # Returns: array([11, 22, 33])
a * b  # Returns: array([10, 40, 90])
a ** 2 # Returns: array([100, 400, 900])
```

### 2. Universal Functions (ufuncs)
NumPy includes highly optimized built-in mathematical functions that perform an operation on every single element inside an array at lightning speed.

* **`np.sqrt(arr)`** ➡️ Computes the square root of each element.
* **`np.exp(arr)`** ➡️ Computes the exponential (\(e^x\)) of each element.
* **`np.log(arr)`** ➡️ Computes the natural logarithm of each element.
* **`np.sin(arr)` / `np.cos(arr)`** ➡️ Computes trigonometric sine/cosine (expects radians).

### 3. What is Broadcasting? ➡️ The "Stretching" Rule
Broadcasting allows you to perform arithmetic between arrays of **different shapes**. NumPy treats the smaller array as if it is cloned or stretched to match the larger array's size.

#### Case A: Array and a Scalar (Single Number)
If you add a single number to an array, the scalar is "stretched" to match the entire array shape.
```python
arr = np.array([1, 2, 3])
arr + 5  # Becomes: [1, 2, 3] + [5, 5, 5] -> Returns: array([6, 7, 8])
```

#### Case B: 2D Matrix and a 1D Vector
If you add a 1D row vector to a 2D matrix, the row vector gets cloned and added to **every single row** of the matrix.
```python
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
row = np.array([10, 20, 30])

matrix + row  # Adds [10, 20, 30] to Row 1 AND Row 2
# Returns: array([[11, 22, 33], 
#                 [14, 25, 36]])
```

---

### 🚨 Handling Special Math Warnings (NaN and Inf)
In native Python, dividing by zero crashes your program. **NumPy will not crash.** Instead, it returns special placeholders and gives a runtime warning:

* **`nan` (Not a Number):** Occurs during mathematically undefined operations, like `0 / 0`.
* **`inf` (Infinity):** Occurs when you divide a positive number by zero, like `1 / 0`.

---

### Quick Operation Summary

| Math Code | Operation Type | Result Behavior |
| :--- | :--- | :--- |
| `arr1 + arr2` | Element-wise | Adds items with matching indices together |
| `arr * 2` | Broadcasting | Multiplies every single element by 2 |
| `np.abs(arr)` | Universal Function | Turns all negative values into positive values |
| `matrix @ matrix` | Matrix Product | Performs actual **Dot Product / Matrix Multiplication** |


In [170]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [171]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [172]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [173]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [174]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [175]:
a1 // a2

array([0, 0, 0, 0, 0])

In [176]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

# BROAD CASTING

# NumPy Broadcasting Deep-Dive

**Broadcasting** is the magic mechanism that allows NumPy to perform arithmetic operations on arrays of **different shapes**. Instead of creating expensive copies of data in memory, NumPy virtually "stretches" the smaller array to match the shape of the larger one.

---

### 1. The Two Golden Rules of Broadcasting
Two dimensions are compatible and can broadcast together **only** if they meet one of these conditions when compared from **right to left (trailing dimensions)**:

1. **They are completely equal** (e.g., both are 4 elements wide).
2. **One of them is exactly 1**. (An axis with a size of `1` is the one that gets stretched).

If neither condition is met, NumPy will throw a `ValueError: operands could not be broadcast together`.

---

### 2. Common Broadcasting Scenarios

#### Scenario A: Array and a Scalar (0D Array)
The single number is stretched dynamically to match every single spot in the array.
```python
arr = np.array([10, 20, 30])  # Shape: (3,)
arr * 2                       # 2 is treated as [2, 2, 2]
# Output: array([20, 40, 60])
```

#### Scenario B: 2D Matrix and a 1D Row Vector
A 1D vector is stretched **downwards** across all rows.
```python
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])  # Shape: (2, 3)
row = np.array([10, 20, 30])    # Shape: (3,)

matrix + row  
# 'row' stretches into: [[10, 20, 30], 
#]
# Output: array([[11, 22, 33], 
#                [14, 25, 36]])
```

#### Scenario C: Row Vector and Column Vector (Grid Building)
If you combine a row vector and a column vector, **both** stretch to form a brand new 2D grid matrix!
```python
row = np.array([1, 2, 3])       # Shape: (3,)
col = np.array([[10], 
                [20]])          # Shape: (2, 1)

row + col
# 'row' stretches down to (2, 3): [[1, 2, 3], [1, 2, 3]]
# 'col' stretches right to (2, 3): [[10, 10, 10], [20, 20, 20]]
# Output: array([[11, 12, 13], 
#                [21, 22, 23]])
```

---

### 3. Will It Broadcast? Compatibility Guide

| Array A Shape | Array B Shape | Can they broadcast? | Resulting Shape | Why? |
| :--- | :--- | :--- | :--- | :--- |
| **`(4, 3)`** | **`(3,)`** |  **Yes** | `(4, 3)` | Right-most dims match (`3` and `3`). Array B stretches to 4 rows. |
| **`(4, 3)`** | **`(4,)`** | ❌ **No** | *Fails* | Right-most dims (`3` and `4`) don't match, and neither is `1`. |
| **`(4, 1)`** | **`(1, 3)`** |  **Yes** | `(4, 3)` | Both have a dimension of `1`. They stretch into each other. |
| **`(2, 2, 3)`** | **`(2, 3)`** |  **Yes** | `(2, 2, 3)` | Trailing dimensions match perfectly. |

---

### 💡 Pro-Tip: Forcing Column Broadcasting with `np.newaxis`
If you have a 1D vector and want to stretch it **sideways** across columns instead of down across rows, use `np.newaxis` to force it into a column shape `(N, 1)` first:

```python
matrix = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
vec = np.array([10, 20])            # Shape: (2,)

# This fails: matrix + vec (adds to rows, but what if we want to add to columns?)
# Fix: Force vec to become a column vector of shape (2, 1)
matrix + vec[:, np.newaxis] 
```


In [177]:
l = [10,20,30,40]
arr = np.array(l)
for i in l:
    print(i + 10)
    

20
30
40
50


In [178]:
arr + 10

array([20, 30, 40, 50])

In [179]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [180]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

# DEEP AND SHALLOW COPY

# NumPy Memory Management: Shallow Copy vs. Deep Copy

NumPy is built for speed and big data. To save RAM, it often creates "views" (pointers to the same memory) instead of making actual duplicates of your data.

---

### 1. No Copy at All (Simple Assignment)
When you assign an array to a new variable name using `=`, no new data is created. Both variables point to the **exact same memory address**.
* **What happens:** Changing `b` completely changes `a`.
```python
a = np.array([1, 2, 3])
b = a  # No copy!
b[0] = 99  # 'a' is now array([99,  2,  3])
```

### 2. Shallow Copy (The NumPy "View")
A **View** creates a new array object, but it still **looks at the exact same data** as the original array. 
* **When does this happen automatically?** **Slicing always creates a view!** (e.g., `arr[1:4]`)
* **What happens:** If you modify elements in a slice/view, you **permanently alter** the original array.
```python
a = np.array([10, 20, 30, 40])
view_arr = a[1:3]  # This is a view!
view_arr[0] = 99   # Modifies index 1 of 'a'
# 'a' is now array([10, 99, 30, 40])
```
*💡 **Note:** You can explicitly force a view using `view_arr = a.view()`.*

### 3. Deep Copy (The True Duplicate)
A **Deep Copy** creates a completely independent mirror image of the array. It copies the structure *and* duplicates all the numbers into a brand-new slot in your computer's RAM.
* **How to do it:** Use the **`.copy()`** method.
* **What happens:** Changing the copied array has **zero effect** on the original array.
```python
a = np.array([1, 2, 3])
deep_copy = a.copy()  # True independent copy!
deep_copy[0] = 99     
# 'a' remains safely untouched: array([1, 2, 3])
```

---

### 🔍 How to Check: The `.base` Attribute
If you aren't sure whether your array is a View or a Deep Copy, check its `.base` attribute:
* If it returns `None`, it is the **original array** or a **Deep Copy** (it owns its data).
* If it returns the original array structure, it is a **View** (it borrows data from a base array).

```python
print(view_arr.base)  # Returns the original array elements
print(deep_copy.base) # Returns None
```

---

### Memory Comparison Summary

| Action Type | Code Syntax | Does it share data with original? | Safely modifies data? |
| :--- | :--- | :--- | :--- |
| **Assignment** | `b = a` | 🔄 Yes (Exactly same object) | ❌ No (Overwrites original) |
| **Slicing / View** | `b = a[0:2]` | 🔄 Yes (Shared memory pool) | ❌ No (Overwrites original) |
| **Deep Copy** | `b = a.copy()` | ❌ No (Brand new allocation) |  **Yes (Original is safe)** |


## In numpy, the concept of shallow and deep copy are directly tried to how the library manages memory views and copy 
- Because Numpy is designed to handle massivr data sets effeciently. It avoids dublicates data in memory useeless you explicitly ask it to....

## 1. Assignment

In [181]:
a = np.array([1,2,3])
b = a
b[0] = 99
print(a)

[99  2  3]


## 2. Shallow copy

In [182]:
a = np.array([1,2,3])
b = a.view()
b[0] = 99
print(a)

[99  2  3]


## Deep copy

In [183]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 99
print(a)   # `a` stay the same

[1 2 3]


# MATRIX OPERATIONS

# NumPy Matrix Operations (Linear Algebra)

Matrix operations handle actual **linear algebra calculations**. In NumPy, there is a massive difference between doing basic element-by-element math and doing true matrix mathematics.

---

### 1. Element-Wise vs. True Matrix Multiplication
This is the most important distinction when working with grids of numbers:

* **Element-Wise Product (`A * B`)** ➡️ Multiplies matching positions. 
  * *Rule:* Both matrices must be the **exact same shape** (or broadcastable).
* **Matrix Dot Product (`A @ B` or `np.dot(A, B)`)** ➡️ Performs row-by-column multiplication.
  * *Rule:* The number of **columns in Matrix A must match the number of rows in Matrix B** (Inner dimensions must match: `(M, N) @ (N, P) -> (M, P)`).

```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Element-wise: [1*5, 2*6] -> [[5, 12], [21, 32]]
print(A * B) 

# True Dot Product: [1*5 + 2*7, 1*6 + 2*8] -> [[19, 22], [43, 50]]
print(A @ B) 
```

### 2. The Transpose (`matrix.T`)
* **What it does:** Flips a matrix over its diagonal, turning all **rows into columns** and columns into rows.
* **Shape shift:** A matrix of shape `(3, 2)` automatically becomes shape `(2, 3)`.

### 3. The Linear Algebra Submodule (`np.linalg`)
For advanced matrix operations, NumPy includes a dedicated toolkit called `np.linalg`.

* **`np.linalg.inv(A)`** ➡️ Computes the **Inverse** of a square matrix (A⁻¹), such that A × A⁻¹ = I (Identity Matrix).
  * *⚠️ Note:* Will throw an error if the matrix is singular (determinant is 0).
* **`np.linalg.det(A)`** ➡️ Calculates the **Determinant** of a square matrix.
* **`np.linalg.eig(A)`** ➡️ Computes the **Eigenvalues and Eigenvectors**.
* **`np.linalg.solve(A, b)`** ➡️ Instantly solves systems of **linear equations** (e.g., Ax = b).

---

### Quick Syntax Lookup Table

| Operation | NumPy Code Syntax | Math Symbol | Shape Requirement |
| :--- | :--- | :--- | :--- |
| **Element-wise Multiplication** | `A * B` | \(\odot\) | Identical shapes |
| **Matrix Multiplication** | `A @ B` or `np.dot(A, B)` | ⋅ or × | Inner dimensions match |
| **Transpose** | `A.T` | \(A^T\) | Any shape |
| **Matrix Inverse** | `np.linalg.inv(A)` | A⁻¹ | Square matrix (`N x N`) |
| **Identity Matrix** | `np.eye(3)` | I | Generates a 3x3 diagonal grid of `1`s |


In [184]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [185]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [186]:
A @ B

array([[19, 22],
       [43, 50]])

In [187]:
A * B

array([[ 5, 12],
       [21, 32]])

In [188]:
A.T

array([[1, 3],
       [2, 4]])

# ADVANCE ARRAY MANIPULATION.

# Advanced NumPy Array Manipulation 

Advanced array manipulation involves changing array structures, merging or splitting data pools, and filtering items programmatically.

---

### 1. Stacking and Concatenating (Joining Arrays)
These methods combine multiple independent arrays into a single dataset.

* **`np.concatenate((a, b), axis=0)`** ➡️ Joins a list of arrays along an existing axis. 
  * `axis=0` stacks them vertically (adds rows).
  * `axis=1` joins them horizontally (adds columns).
* **`np.vstack((a, b))` (Vertical Stack)** ➡️ Stacks arrays on top of each other. Shortcut for concatenating along axis 0.
* **`np.hstack((a, b))` (Horizontal Stack)** ➡️ Stacks arrays side-by-side. Shortcut for concatenating along axis 1.

### 2. Advanced Splitting
The inverse of stacking—chopping a single array into multiple smaller sub-arrays.

* **`np.vsplit(arr, sections)`** ➡️ Splits an array vertically (cuts horizontally across rows).
* **`np.hsplit(arr, sections)`** ➡️ Splits an array horizontally (cuts vertically across columns).

### 3. Adding and Removing Elements
* **`np.append(arr, values, axis=None)`** ➡️ Appends values to the end of an array. If no axis is specified, it collapses the output into a flat 1D array.
* **`np.insert(arr, index, values, axis=None)`** ➡️ Inserts elements at a specific index position along a given axis.
* **`np.delete(arr, index, axis=None)`** ➡️ Removes a sub-array or element at a designated index.

### 4. Advanced Conditioning: `np.where()` & `np.select()`
Instead of just filtering with true/false masks, these functions apply structural logic.

* **`np.where(condition, x, y)`** ➡️ Read as: *"Where condition is True, give me `x`, otherwise give me `y`"*. Great for binary decisions.
  ```python
  # Change all values > 50 to 1, and everything else to 0
  np.where(arr > 50, 1, 0)
  ```
* **`np.select(condlist, choicelist, default=0)`** ➡️ Evaluates multiple sequential conditions. Matches a list of logic states to a list of distinct outcomes.

---

### Quick Syntax Lookup Table

| Function | Action Type | Common Use Case |
| :--- | :--- | :--- |
| `np.vstack((a, b))` | Joining | Adding new rows of data observations |
| `np.hstack((a, b))` | Joining | Adding new feature columns to an existing matrix |
| `np.hsplit(matrix, 2)` | Splitting | Breaking a dataset into equal Left and Right halves |
| `np.where(arr < 0, 0, arr)` | Conditional | Relu activation style filter (Clips values below zero to 0) |


In [189]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [190]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [191]:
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [192]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [193]:
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [194]:
matrix = np.arange(16).reshape(4,4)

In [195]:
np.hsplit(matrix, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]